apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
  - image: almalinux
    name: sidecar
    command: ['sleep', '200']
